// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdpbgljdsvstnvzmdtfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkcGJnbGpkc3ZzdG52em1kdGZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MzQ0MDAsImV4cCI6MjA3MjExMDQwMH0.oCtzN7MHwfWiwoSkH0eaWrhGEwkB7MlmARQkpbg0SAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});